project:
  type: website
    
website:
  site-url: https://archaeothommy.github.io/
  repo-url: https://github.com/archaeothommy/archaeothommy.github.io/
  favicon: favicon.png
  title: "Thomas Rose"
  navbar:
    left:
      - text: "My research"
        href: index.qmd
      - text: "About me"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  